onboarding = false
[theme]
name = "nord"
auto_switch = false

[theme.custom]
subtext0 = "#abaca9"

[keys]
prefix = "ctrl+t"

[experimental]
switch_ascii_input_source_in_prefix = true
pane_history = true

[ui]
agent_panel_sort = "priority"

[ui.sidebar.spaces]
rows = [["state_icon", { token = "workspace", fg = "#eff0eb" }], [{ token = "branch", fg = "#898a88" }, "git_status"]]

[ui.sidebar.agents]
rows = [["state_icon", "workspace", { token = "tab", fg = "#abaca9" }], [{ token = "agent", fg = "#abaca9" }]]
