cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "asdf"
brew "bat"
brew "bottom"
brew "cmake"
brew "colordiff"
brew "curl"
brew "direnv"
brew "exa"
brew "fd"
brew "gawk"
brew "ghq"
brew "gibo"
brew "git"
brew "git-secrets"
brew "go"
brew "httpie"
brew "jid"
brew "jo"
brew "jq"
brew "mas"
brew "mercurial"
brew "mergepbx"
brew "mysql"
brew "neovim"
brew "nkf"
brew "nmap"
brew "ossp-uuid"
brew "peco"
brew "remarshal"
brew "sheldon"
brew "sqlite"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"

cask "1password"
cask "appcleaner"
cask "caffeine"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "krisp"
cask "obsidian"
cask "qlmarkdown"
cask "raycast"
cask "sequel-ace"
cask "spotify"
cask "visual-studio-code"

cask "font-camingocode"
cask "font-go"
cask "font-hackgen"
cask "font-jetbrains-mono"
cask "font-myricam"
cask "font-ricty-diminished"

mas "CotEditor", id: 1024640650
mas "Magnet", id: 441258766
mas "MindNode", id: 1289197285
