cask_args appdir: "/Applications"

tap "homebrew/bundle"

brew "bat"
brew "bottom"
brew "cmake"
brew "colordiff"
brew "curl"
brew "direnv"
brew "eza"
brew "fd"
brew "gawk"
brew "ghq"
brew "gibo"
brew "git"
brew "git-secrets"
brew "httpie"
brew "jo"
brew "jq"
brew "mas"
brew "mise"
brew "neovim"
brew "nmap"
brew "ossp-uuid"
brew "peco"
brew "sheldon"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"

cask "1password"
cask "appcleaner"
cask "arc"
cask "caffeine"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "krisp"
cask "logi-options+"
cask "obsidian"
cask "qlmarkdown"
cask "raycast"
cask "sequel-ace"
cask "visual-studio-code"

cask "font-camingocode"
cask "font-hackgen"
cask "font-jetbrains-mono"

mas "CotEditor", id: 1024640650
mas "Magnet", id: 441258766
