shell = "zsh"

apply = ["defer"]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']


[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ['source']

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'

[plugins.colors]
inline = 'autoload -Uz colors && zsh-defer colors'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.git-open]
github = "paulirish/git-open"

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"

[plugins.dotfiles-sync]
local = "~/.config/zsh/sync"
use = ["*.zsh"]
apply = ["source"]

[plugins.dotfiles-defer]
local = "~/.config/zsh/defer"
use = ["*.zsh"]
