- name: uninstall rbenv, pyenv, go
  homebrew:
    name: "{{ item }}"
    state: absent
  with_items:
    - go
    - pyenv
    - rbenv
    - ruby-build
  when: ansible_distribution == 'MacOSX'

- stat:
    path: ~/.anyenv
  register: anyenv_dir

- name: git clone
  git:
    clone: yes
    repo: https://github.com/riywo/anyenv
    dest: ~/.anyenv
  when: not anyenv_dir.stat.exists

- name: create plugins directory
  file:
    path: ~/.anyenv/plugins
    state: directory

- stat:
    path: ~/.anyenv/plugins/anyenv-update
  register: update_dir

- name: git clone anyenv-update
  git:
    clone: yes
    repo: https://github.com/znz/anyenv-update.git
    dest: ~/.anyenv/plugins/anyenv-update
  when: not update_dir.stat.exists

- name: set shell
  copy:
    src: anyenv.sh
    dest: ~{{ user }}/.zsh.d/anyenv.sh
    mode: "644"
