- name: set brew shell
  copy:
    src: brew.sh
    dest: ~{{ user }}/.zsh.d/brew.sh
    mode: "644"

- name: export
  shell: source ~/.zshrc

- name: brew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: brew_taps

- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: brew install
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: brew_packages

- name: brew cask install
  homebrew:
    name: brew-cask
    state: latest

- name: brew install cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: cask_packages

- name: brew install font packages
  homebrew_cask:
    name: "font-{{ item }}"
    state: present
  with_items: font_packages
