#!/bin/zsh

export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$JAVA_HOME'"' | sed 's/:$//'`

echo $1
export JAVA_HOME=`/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java_home -v "$1"`
export PATH=${JAVA_HOME}/bin:${PATH}
