#!/bin/zsh

nodebrew install-binary latest;
nodebrew use latest;
npm i babel babel-cli gulp-cli eslint babel-eslint eslint-plugin-react eslint-config-airbnb npm-check-updates coffee-script bower typescript tsd fixpack -g;
