#!/bin/zsh

nodebrew install-binary latest;
nodebrew use latest;
npm i -g \
  babel-eslint \
  eslint \
  eslint-plugin-react \
  70-10/eslint-config-default \
  fast-cli \
  fixpack \
  flow-bin \
  ngrok \
  npm-check \
  serverless \
  yarn;
