dotfiles:
  - ".zlogin"
  - ".zlogout"
  - ".zprofile"
  - ".zshenv"
  - ".zsh.d"
  - ".zshrc"
  - ".gitconfig"
  - ".gitattributes"
  - ".gitignore_global"
  - ".editorconfig"
  - ".eslintrc"
  - ".atom"
  - ".npmrc"
  - ".tmux.conf"
  - ".vimrc"
