[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = "lts"
rust = "stable"
uv = "latest"
aws-cli = "latest"
ni = "latest"

"npm:@github/copilot" = "latest"
"npm:clipboard-cli" = "latest"
"npm:trash-cli" = "latest"
"npm:git-graftree" = "latest"
"npm:pnpm" = "latest"

"npm:opencode-ai" = "latest"
